const prodGamesList = ["SlidingPuzzle",
    "BricksBreaker",
    "Snake",
    "ClickTheDifferentColor",
    "MathPuzzle",
    "DuckHunt",
    "TossTheCan",
    "Go-around", "CutTheRope", "CadburyGems(Memorydots)",
    "platformer-mickey-cheese", "Spaceshooter", "HappyB", "petGame", "WordDice",
    "Airshipadventure.js",
    "AngryBirds.js",
    "BoxTower.js",
    "Bridgebuilder.js",
    "CandyCrush.js",
    "CannonBalls.js",
    "CannonShooter.js",
    "cardMemory.js",
    "ChromeDinoRun.js",
    "CrossyRoad.js",
    "Darts.js",
    "DownhillSki.js",
    "FightOn.js",
    "FlappyBird.js",
    "FruitNinja.js",
    "Harpoon.js",
    "HillClimbRacing.js",
    "Mariobros.js",
    "MessidodgeCorona.js",
    "Platformer(infiniteverticaljumping).js",
    "Pong.js",
    "Racing.js",
    "RiseUp.js",
    "Rogue.js",
    "saveEarth.js",
    "SpaceInvader.js",
    "SpinMaster.js",
    "SwingMania.js",
    "TaptoSave.js",
    "TowerDefence(Arcade-shooting-health).js",
    "Whack-a-Mole.js",
    "Go-around.js",
    "CutTheRope.js",

    "NinjaBlades.js"
]

export default prodGamesList;

