const prodGamesList = [
    "CandyCrush",
    "ChromeDinoRun",
    "SpaceInvader",
    "FruitNinja",
    "BoxTower",
    "BricksBreaker",
    "FlappyBird",
    "AngryBirds",
    "MessidodgeCorona",
    "Snake",
    "Whack-a-Mole",
    "CadburyGems(Memorydots)",
    "Platformer(infiniteverticaljumping)",
    "Airshipadventure",
    "TowerDefence(Arcade-shooting-health)",
    "Bridgebuilder",
    "CannonShooter",
    "CrossyRoad",
    "SpinMaster",
    "Mariobros",
    "Darts",
    "Harpoon",
    "CannonBalls",
    "SwingMania",
    "DownhillSki",
    "HillClimbRacing",
    "FightOn",
    "Racing",
    "RiseUp",
    "TaptoSave",
    "Rogue",
]

export default prodGamesList;